# Generated by Django 2.1.1 on 2018-09-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name_plural': 'Publicações'},
        ),
    ]
